using Npgsql;

namespace ProxyWard.Audit.Sinks;

public static class PostgresAuditSchema
{
    public const string SchemaSql = """
        CREATE TABLE IF NOT EXISTS audit_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            timestamp_utc TEXT NOT NULL,
            event_type TEXT NOT NULL,
            mode TEXT NOT NULL,
            decision TEXT NOT NULL,
            server_id TEXT NOT NULL,
            method TEXT NULL,
            tool_name TEXT NULL,
            reasons TEXT NOT NULL,
            policy_version TEXT NOT NULL,
            correlation_id TEXT NOT NULL,
            request_bytes BIGINT NOT NULL,
            duration_ms BIGINT NOT NULL,
            payload_json JSONB NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_audit_events_timestamp ON audit_events(timestamp_utc);
        CREATE INDEX IF NOT EXISTS idx_audit_events_decision ON audit_events(decision);
        CREATE INDEX IF NOT EXISTS idx_audit_events_server_id ON audit_events(server_id);
        CREATE INDEX IF NOT EXISTS idx_audit_events_method ON audit_events(method);
        CREATE INDEX IF NOT EXISTS idx_audit_events_tool_name ON audit_events(tool_name);
        CREATE INDEX IF NOT EXISTS idx_audit_events_reasons ON audit_events(reasons);
        """;

    public static async Task EnsureSchemaAsync(
        NpgsqlConnection connection,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(connection);

        await using var schema = connection.CreateCommand();
        schema.CommandText = SchemaSql;
        await schema.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }
}
